name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --all-targets

      - name: Test
        run: cargo test

  coverage:
    runs-on: docker
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin --locked

      - name: Run coverage
        run: cargo tarpaulin --fail-under 100
